### PR TITLE
Database migrations + other dev stuff & bug fixes

### LINKED ISSUE #44: Add endpoint to search users by username

### PR DESCRIPTION
**Pull request by Saeraphinx**
Credits to @TheUnifox for implementing uzmug & database migrations (#49)

closes #44
unblocks #32 #33 #47 #48

### CODE REVIEW

File: src/shared/migrations/000-init.ts [hunk 1]
```diff
@@ -0,0 +1,318 @@
...
+            type: DataTypes.TEXT,
+            allowNull: false,
+            defaultValue: `community`,
+        },
+        authorId: {
+            type: DataTypes.INTEGER,
+            allowNull: false,
+        },
+        createdAt: DataTypes.DATE, // just so that typescript isn't angy
+        updatedAt: DataTypes.DATE,
```
Comment (Saeraphinx) [inline src/shared/migrations/000-init.ts:307]: missing deleted at for `motds` table
